# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='明星名称')),
                ('key_words', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('introduce', models.TextField(blank=True, max_length=255, null=True, verbose_name='介绍')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='img_avatar/%Y-%m-%d', verbose_name='头像的url')),
                ('cps', models.FloatField(blank=True, null=True, verbose_name='明星CPS佣金')),
                ('gender', models.CharField(choices=[('A', '不限'), ('B', '女'), ('C', '男'), ('D', '其他')], default='C', max_length=1, verbose_name='性别')),
                ('create_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_star',
                'verbose_name': '明星',
                'verbose_name_plural': '明星',
            },
        ),
        migrations.CreateModel(
            name='StarWeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='微博名称')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='微博地址')),
                ('fans_num', models.IntegerField(blank=True, null=True, verbose_name='粉丝数')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star.Star')),
            ],
            options={
                'db_table': 't_star_weibo',
                'verbose_name': '明星微博信息',
                'verbose_name_plural': '明星微博信息',
            },
        ),
        migrations.CreateModel(
            name='StarWeixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信名')),
                ('weixinid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信id')),
                ('fans_num', models.IntegerField(blank=True, null=True, verbose_name='粉丝数')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('memo', models.CharField(blank=True, max_length=11, null=True, verbose_name='备注')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star.Star')),
            ],
            options={
                'db_table': 't_star_weixin',
                'verbose_name': '明星微信信息',
                'verbose_name_plural': '明星微信信息',
            },
        ),
        migrations.CreateModel(
            name='StarZhiArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_star_zhiarea',
                'verbose_name': '基础数据-明星直播的地域 列表',
                'verbose_name_plural': '基础数据-明星直播的地域 列表',
            },
        ),
        migrations.CreateModel(
            name='StarZhibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='明星在某直播平台中的id')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像url链接')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='直播平台中的昵称')),
                ('is_credibility', models.CharField(choices=[('A', '未认证'), ('B', '已认证')], default='A', max_length=1, verbose_name='认证状态')),
                ('fans_num', models.IntegerField(blank=True, null=True, verbose_name='粉丝数')),
                ('average_num', models.IntegerField(blank=True, null=True, verbose_name='平均观看数')),
                ('reads_num', models.IntegerField(blank=True, null=True, verbose_name='订阅量')),
                ('export_price', models.FloatField(blank=True, null=True, verbose_name='口头播放价格')),
                ('ad_implants_price', models.FloatField(blank=True, null=True, verbose_name='商品植入价格')),
                ('brand_exposed_price', models.FloatField(blank=True, null=True, verbose_name='品牌漏出价格')),
                ('memo', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='star.StarZhiArea', verbose_name='地域')),
            ],
            options={
                'db_table': 't_star_zhibo',
                'verbose_name': '明星直播信息',
                'verbose_name_plural': '明星直播信息',
            },
        ),
        migrations.CreateModel(
            name='StarZhiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_star_zhicategory',
                'verbose_name': '基础数据-明星直播的分类 列表',
                'verbose_name_plural': '基础数据-明星直播的分类 列表',
            },
        ),
        migrations.CreateModel(
            name='StarZhiFansNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_star_zhifansnum',
                'verbose_name': '基础数据-明星直播的粉丝数 列表',
                'verbose_name_plural': '基础数据-明星直播的粉丝数 列表',
            },
        ),
        migrations.CreateModel(
            name='StarZhiPlatForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_star_zhipaltform',
                'verbose_name': '基础数据-明星直播的平台 列表',
                'verbose_name_plural': '基础数据-明星直播的平台 列表',
            },
        ),
        migrations.CreateModel(
            name='StarZhiPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_star_zhiprice',
                'verbose_name': '基础数据-明星直播的参考报价 列表',
                'verbose_name_plural': '基础数据-明星直播的参考报价 列表',
            },
        ),
        migrations.AddField(
            model_name='starzhibo',
            name='broadcast_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='star.StarZhiPlatForm', verbose_name='直播平台'),
        ),
        migrations.AddField(
            model_name='starzhibo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='star.StarZhiCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='starzhibo',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_zhibo', to='star.Star', verbose_name='明星'),
        ),
    ]
