# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20160912_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('A', '未审核'), ('B', '已审核')], default='A', max_length=1, verbose_name='充值状态'),
        ),
    ]
