# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='微博素材名称')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='微博文字内容')),
                ('picture', models.CharField(blank=True, max_length=255, null=True, verbose_name='微博图片路径')),
                ('goods_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品链接url')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_user', models.CharField(max_length=100, verbose_name='创建者')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微博素材',
                'verbose_name_plural': '微博素材',
                'db_table': 't_creative_weibo',
            },
        ),
        migrations.CreateModel(
            name='CreativeWeixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信标题')),
                ('anthor', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信作者')),
                ('file_picture_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图的url')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='文字素材内容')),
                ('create_user', models.IntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信素材',
                'verbose_name_plural': '微信素材',
                'db_table': 't_creative_weixin',
            },
        ),
        migrations.CreateModel(
            name='CreativeZhibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upload', models.CharField(choices=[('A', '已上传'), ('B', '未上传')], default='B', max_length=1, verbose_name='素材上传状态')),
                ('outer_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='外链url')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='直播名称')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='口播广告内容')),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='植入商品名称')),
                ('goods_url', models.ImageField(upload_to='img_goods/%Y-%m-%d/%H-%M-%S/', verbose_name='植入商品图像的url')),
                ('archive_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='压缩包url')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('is_delete', models.IntegerField(blank=True, default=0, null=True, verbose_name='素材的删除状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.CharField(max_length=100, verbose_name='创建者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('update_user', models.CharField(max_length=100, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '直播素材',
                'verbose_name_plural': '直播素材',
                'db_table': 't_creative_zhibo',
            },
        ),
        migrations.CreateModel(
            name='StarOrCelebrityCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_type', models.IntegerField(blank=True, null=True, verbose_name='素材类型')),
                ('relate_type', models.CharField(choices=[('S', '明星'), ('C', '红人')], max_length=1, verbose_name='类型--明星或者红人')),
                ('star_or_celebrity_id', models.IntegerField(verbose_name='明星或者红人id')),
                ('creative_id', models.IntegerField(blank=True, null=True, verbose_name='素材id')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '红人或者明星 与素材的关联',
                'verbose_name_plural': '红人或者明星 与素材的关联',
                'db_table': 't_star_or_celebrity_creative',
            },
        ),
    ]
