# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('star', '0001_initial'),
        ('creative', '0001_initial'),
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('advertiser_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='广告主')),
                ('budget', models.FloatField(verbose_name='总预算')),
                ('memo', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('activity_status', models.CharField(choices=[('A', '待审核'), ('B', '待上传素材'), ('C', '已通过审核,待接单'), ('D', '已支付'), ('E', '投放中'), ('F', '投放结束,待接单'), ('G', '已结算'), ('H', '已关闭')], default='A', max_length=1, verbose_name='活动状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('update_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='修改者')),
            ],
            options={
                'db_table': 't_activity',
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Flighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='选择时间')),
                ('plat', models.CharField(blank=True, max_length=255, null=True, verbose_name='选择平台')),
                ('start_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义排期开始时间')),
                ('end_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义排期结束时间')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creative.CreativeZhibo', verbose_name='素材')),
            ],
            options={
                'db_table': 't_flighting',
                'verbose_name': '排期',
                'verbose_name_plural': '排期',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='订单名称')),
                ('status', models.CharField(choices=[('A', '未审核'), ('B', '待审核'), ('C', '待付款'), ('D', '已付款'), ('E', '已关闭')], default='C', max_length=1, verbose_name='订单状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='订单投放开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='订单投放结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单创建者')),
                ('order_add_id', models.IntegerField(verbose_name='order_add 的id')),
                ('order_pay', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单报价总价支付金额')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_order', to='activity.Activity', verbose_name='活动名称')),
            ],
            options={
                'db_table': 't_order',
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Order_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='粉丝量-保底佣金')),
                ('cps', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPS')),
                ('activity_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动ID')),
                ('celebrityzhibo_id', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True, verbose_name='网红直播信息')),
                ('starzhibo_id', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True, verbose_name='明星直播信息')),
                ('creativezhibo_id', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True, verbose_name='直播素材的id 集合')),
            ],
            options={
                'db_table': 't_order_add',
                'verbose_name': '订单附加表',
                'verbose_name_plural': '订单附加表',
            },
        ),
        migrations.CreateModel(
            name='OrderCelebrityShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='记录创建时间')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrity.Celebrity', verbose_name='红人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Order', verbose_name='订单')),
            ],
            options={
                'db_table': 't_order_celebrity',
                'verbose_name': '订单与 红人的关联',
                'verbose_name_plural': '订单与 红人的关联',
            },
        ),
        migrations.CreateModel(
            name='OrderStarShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='记录创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Order', verbose_name='订单')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='star.Star', verbose_name='明星')),
            ],
            options={
                'db_table': 't_order_star',
                'verbose_name': '订单与 明星的关联',
                'verbose_name_plural': '订单与 明星的关联',
            },
        ),
    ]
