# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='网红名')),
                ('key_words', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('introduce', models.TextField(blank=True, max_length=255, null=True, verbose_name='介绍')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='img_avatar/%Y-%m-%d', verbose_name='头像的url')),
                ('cps', models.FloatField(blank=True, null=True, verbose_name='CPS')),
                ('is_busy', models.IntegerField(blank=True, null=True, verbose_name='活动状态')),
                ('gender', models.CharField(choices=[('0', '不限'), ('1', '女'), ('2', '男'), ('3', '其他')], default='2', max_length=1, verbose_name='性别')),
                ('create_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 't_celebrity',
                'verbose_name': '网红',
                'verbose_name_plural': '网红',
            },
        ),
        migrations.CreateModel(
            name='CelebrityWeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(blank=True, null=True, verbose_name='类型')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='昵称')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='url链接')),
                ('fans_num', models.IntegerField(blank=True, null=True, verbose_name='粉丝数')),
                ('is_authentication', models.IntegerField(blank=True, null=True, verbose_name='认证状态')),
                ('forward_place', models.FloatField(blank=True, null=True, verbose_name='转发价格')),
                ('direct_price', models.FloatField(blank=True, null=True, verbose_name='直发价格')),
                ('memo', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrity.Celebrity')),
            ],
            options={
                'db_table': 't_celebrity_weibo',
                'verbose_name': '网红微博信息',
                'verbose_name_plural': '网红微博信息',
            },
        ),
        migrations.CreateModel(
            name='CelebrityWeixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(blank=True, null=True, verbose_name='微信类型')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号名称')),
                ('weixinid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信id')),
                ('fans_num', models.IntegerField(verbose_name='粉丝数')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='参考价格')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='投放位置')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='推荐指数')),
                ('scan_num', models.IntegerField(blank=True, null=True, verbose_name='阅读量参考')),
                ('is_reserve', models.IntegerField(blank=True, null=True, verbose_name='是否接受预定')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('memo', models.TextField(blank=True, max_length=11, null=True, verbose_name='备注')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrity.Celebrity')),
            ],
            options={
                'db_table': 't_celebrity_weixin',
                'verbose_name': '网红微信信息',
                'verbose_name_plural': '网红微信信息',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhiArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_celebrity_zhiarea',
                'verbose_name': '基础数据-网红直播的地域 列表',
                'verbose_name_plural': '基础数据-网红直播的地域 列表',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='网红在某直播平台中的id')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像url链接')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='直播平台中的昵称')),
                ('is_credibility', models.CharField(choices=[('A', '未认证'), ('B', '已认证')], default='A', max_length=1, verbose_name='认证状态')),
                ('fans_num', models.IntegerField(blank=True, null=True, verbose_name='粉丝数')),
                ('average_num', models.IntegerField(blank=True, null=True, verbose_name='平均观看数')),
                ('reads_num', models.IntegerField(blank=True, null=True, verbose_name='订阅量')),
                ('export_price', models.FloatField(blank=True, null=True, verbose_name='口头插播价格')),
                ('ad_implants_price', models.FloatField(blank=True, null=True, verbose_name='商品露出价格')),
                ('brand_exposed_price', models.FloatField(blank=True, null=True, verbose_name='品牌植入价格')),
                ('memo', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('sid', models.IntegerField(verbose_name='红人头像id')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrity.CelebrityZhiArea', verbose_name='地域')),
            ],
            options={
                'db_table': 't_celebrity_zhibo',
                'verbose_name': '网红直播信息',
                'verbose_name_plural': '网红直播信息',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_celebrity_zhicategory',
                'verbose_name': '基础数据-网红直播的分类 列表',
                'verbose_name_plural': '基础数据-网红直播的分类 列表',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhiFansNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_celebrity_zhifansnum',
                'verbose_name': '基础数据-网红直播的粉丝数 列表',
                'verbose_name_plural': '基础数据-网红直播的粉丝数 列表',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhiPlatForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_celebrity_zhiplatform',
                'verbose_name': '基础数据-网红直播的平台 列表',
                'verbose_name_plural': '基础数据-网红直播的平台 列表',
            },
        ),
        migrations.CreateModel(
            name='CelebrityZhiPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(verbose_name='类型id')),
                ('name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 't_celebrity_zhiprice',
                'verbose_name': '基础数据-网红直播的参考报价 列表',
                'verbose_name_plural': '基础数据-网红直播的参考报价 列表',
            },
        ),
        migrations.AddField(
            model_name='celebrityzhibo',
            name='broadcast_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrity.CelebrityZhiPlatForm', verbose_name='直播平台'),
        ),
        migrations.AddField(
            model_name='celebrityzhibo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celebrity.CelebrityZhiCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='celebrityzhibo',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_zhibo', to='celebrity.Celebrity', verbose_name='网红'),
        ),
    ]
