# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(blank=True, null=True, verbose_name='活动id')),
                ('weixin_click', models.IntegerField(blank=True, null=True, verbose_name='微信点击量')),
                ('weibo_click', models.IntegerField(blank=True, null=True, verbose_name='微博点击量')),
                ('zhibo_click', models.IntegerField(blank=True, null=True, verbose_name='直播播出量')),
                ('zhibo_read', models.IntegerField(blank=True, null=True, verbose_name='直播订阅量')),
                ('zhibo_call', models.IntegerField(blank=True, null=True, verbose_name='直播访问量')),
                ('click_time', models.DateTimeField(blank=True, null=True, verbose_name='点击时间')),
                ('exposure_num', models.IntegerField(blank=True, null=True, verbose_name='曝光数')),
                ('exposure_rate', models.FloatField(blank=True, null=True, verbose_name='曝光率')),
                ('click_num', models.IntegerField(blank=True, null=True, verbose_name='点击数')),
                ('click_rate', models.FloatField(blank=True, null=True, verbose_name='点击率')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_order', to='activity.Order', verbose_name='订单id')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 't_report',
            },
        ),
    ]
